services:
  - type: web
    name: api
    branch: main
    env: node
    buildCommand: yarn build:api
    startCommand: yarn start:api
    buildFilter:
      paths:
        - api/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString

  - type: web
    name: web
    branch: main
    env: node
    buildCommand: yarn build:web
    startCommand: yarn start:web
    buildFilter:
      paths:
        - web/**
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: api
          property: host

databases:
  - name: api_db
    databaseName: db
