previewsEnabled: true

services:
  - type: web
    name: api
    branch: deploy-to-render
    env: node
    buildCommand: yarn install && yarn prisma migrate deploy && yarn build:api
    startCommand: yarn start:api
    buildFilter:
      paths:
        - api/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: api_db
          property: connectionString

  - type: web
    name: web
    branch: deploy-to-render
    env: node
    buildCommand: yarn install && yarn build:web:prod
    startCommand: yarn start:web
    buildFilter:
      paths:
        - web/**
    envVars:
      - key: API_RENDER_HOST
        fromService:
          type: web
          name: api
          property: host

databases:
  - name: api_db
    databaseName: db
